config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :menus

end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
    @menu = Menu.find params[:id]
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.create menu_params
    redirect_to root_path
  end

  def edit
    @menu = Menu.find params[:id]
  end

  def update
    @menu = Menu.find params[:id]
    @menu.update_attributes menu_params
    redirect_to root_path
  end

  def destroy
    @menu = Menu.find params[:id]
    @menu.destroy
    redirect_to root_path
  end

private
  def menu_params
    params.require(:menu).permit(
        :name,
        :description,
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/home/index.html.erb
<h1>Restaurant</h1>

<%= link_to "New Menu", new_menu_path %>
<br>
<% @menus.each do |menu| %>
  <br>
  <%= link_to "Menu Info", menu_path(menu) %>
  <br>
  <%= menu.name %>
  <br>
  <%= menu.description %>
  <br>
  <%= link_to "Edit Menu", edit_menu_path(menu) %>
  <br>
  <%= link_to "Delete Menu", menu_path(menu), method: :delete %>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for @menu do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.submit %>
<% end %>

app/views/menus/edit.html.erb
<h1>Edit Menu</h1>

<%= render 'form' %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

app/views/menus/show.html.erb
<h1>Menu Info</h1>

<%= @menu.name %>
<br>
<%= @menu.description %>
<br>
<%= link_to "Home", root_path %>